name: PR Size Labeler

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  label-pr-size:
    name: Apply Size Label
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Apply Size Label
        uses: lukas-kuntze/devx-action-pr-size-labeler@v1
        with:
          config_file: .github/config/size-labels.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
